syntax on
syntax enable

set wildmenu
set visualbell 		" no sounds
set belloff=all		" no bell at all

" max textwith
set textwidth=120

" colored vertical line at column 120
set colorcolumn=+1
highlight ColorColumn ctermbg=0 guibg=lightgrey

" tabs
set shiftwidth=4
set tabstop=4
set softtabstop=4

" statusline
set laststatus=2

set autoindent

set mouse=a 		" enable mouse in all modes	 

set showcmd

set ruler
set number			" line numbers
set relativenumber	" relative line numbering
set autoread 		" reload files if changed outside of vim

set history=1000 	" 1000 elements saved in history 
set nobackup 		" no tilde file generated

"file stuff
set encoding=utf-8

" scrolling
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" backspace
set backspace=indent,eol,start

